name: scanner
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  #  sms_advanced: ^1.1.0
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  mobile_scanner: ^7.0.1
  another_telephony: ^0.4.1
  permission_handler: ^12.0.0+1
  rename_app: ^1.6.3
  flutter_tts: ^4.2.3
  bcrypt: ^1.1.3
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  image_picker: ^1.1.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
